version: "3.7"

services:
  sample-app:
    build: '.'
    expose:
      - 9003
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/
    environment:
      XDEBUG_MODE: develop,debug
      